# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- 2024-08-05Dockerfile

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  envFilePath: '$(Agent.TempDirectory)'
  


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: DownloadSecureFile@1
      name: envfile
      inputs:
        secureFile: '.env.local'



    # - task: CopyFiles@2
    #   inputs:
    #     SourceFolder: '$(envFilePath)'
    #     Contents: .env.local'
    #     TargetFolder: '$(Build.SourcesDirectory)'


    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          FILENAME= 'basename $(envfile,secureFilePath)'
          cp $(envfile.secureFilePath) $(Build.SourcesDirectory)/.env.local
          ls
 
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
          latest
        repository: 'cit-website' 
        container: 'cit-website'
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'aws-azure-devops'
        regionName: 'us-east-1'
        imageSource: 'imagename'
        sourceImageName: 'cit-website'
        repositoryName: 'cit-website2.0-dev'
    
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          package.json
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs: 
        PathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
        ArtifactName: 'release' # output artifact named www
