// Generated by https://quicktype.io

export interface EmployeesContent {
    id:         number;
    created_at: string;
    tittleEn:   string;
    tittleEs:   string;
    captionEn:  string;
    captionEs:  string;
}
